# Generated by Django 3.0.1 on 2020-01-11 06:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='event/photo/', validators=[core.validators.validate_photo_extension])),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
