# Generated by Django 3.0.1 on 2020-01-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200111_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagedatamodel',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
